[versions]
compose = "1.6.5"
activity-compose = "1.8.2"
material3 = "1.2.1"
bom = "2024.04.01"
kotlinCompilerExtension = "1.5.11"
desugar_jdk_libs = "2.1.5"
firebaseAuth = "23.2.1"
firebaseAuthVersion = "23.2.1"
googleAuthLibraryOauth2Http = "1.11.0"
gradle = "8.2.2"
gradleVersion = "8.2.2"
mpandroidchart = "v3.1.0"
playServicesAuthVersion = "21.3.0"
playServicesBase = "21.5.0"
playServicesBaseVersion = "18.7.0"
vertexai = "16.5.0"
agp = "8.12.3"
compiler = "4.15.1"
firebaseBom = "33.15.0"
firebaseBomVersion = "33.15.0"
glide = "4.15.1"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
firebaseAuthKtx = "23.2.1"
firebaseFirestoreKtx = "25.1.4"
materialVersion = "1.12.0"
moshi = "1.12.0"
okhttp = "4.11.0"
playServicesAuth = "21.2.0"
firebaseVertexai = "16.5.0"
workRuntime = "2.10.1"
lifecycle = "2.9.1"
coroutines = "1.7.3"
composeMaterialCore = "1.4.1"
navigationComposeJvmstubs = "2.9.0"
runtimeLivedata = "1.9.2"
mediationTestSuite = "3.0.0"

[libraries]
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
#noinspection SimilarGradleDependency
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
firebase-auth-v2310 = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthVersion" }
#noinspection SimilarGradleDependency
firebase-vertexai = { module = "com.google.firebase:firebase-vertexai", version.ref = "vertexai"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
#noinspection SimilarGradleDependency
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
#noinspection SimilarGradleDependency
firebase-bom-v3210 = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-auth-library-oauth2-http = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuthLibraryOauth2Http" }
#noinspection SimilarGradleDependency
google-firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
google-firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx" }
#noinspection SimilarGradleDependency
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
#noinspection SimilarGradleDependency
gradle-v820 = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
#noinspection SimilarGradleDependency
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
#noinspection SimilarGradleDependency
material-v130alpha03 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
#noinspection SimilarGradleDependency
google-firebase-vertexai = { group = "com.google.firebase", name = "firebase-vertexai", version.ref = "firebaseVertexai" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuthVersion" }
#noinspection SimilarGradleDependency
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
#noinspection SimilarGradleDependency
play-services-base-v1820 = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBaseVersion" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-navigation-compose-jvmstubs = { group = "androidx.navigation", name = "navigation-compose-jvmstubs", version.ref = "navigationComposeJvmstubs" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
mediation-test-suite = { group = "com.google.android.ads", name = "mediation-test-suite", version.ref = "mediationTestSuite" }

[bundles]
compose = [
    "compose-ui",
    "compose-ui-tooling-preview",
    "compose-material3",
    "activity-compose"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
